[package]
name = "agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
bollard = "0.14.0"
futures-util = "0.3.27"
tokio-tungstenite = "0.18.0"
tokio = { version = "1.26.0", features = ["full"] }